(in-package #:claude-agent-sdk-cl)

(defclass filesystem-session-store (session-store)
  ((root :initarg :root :reader filesystem-session-store-root)
   (seen :initform (make-hash-table :test #'equal) :accessor filesystem-store-seen)))

(defun %filesystem-root (root)
  (unless (and (or (stringp root) (pathnamep root))
               (> (length (namestring root)) 0))
    (signal-sdk-input-error "filesystem session-store root must be a non-empty string"))
  (let ((pathname (uiop:ensure-directory-pathname (pathname root))))
    (ensure-directories-exist (merge-pathnames #P".keep" pathname))
    pathname))

(defun make-filesystem-session-store (&key root)
  "Create a session store rooted at ROOT. ROOT is the complete storage boundary."
  (make-instance 'filesystem-session-store :root (%filesystem-root root)))

(defun %filesystem-component (value label &key allow-slashes)
  (unless (and (stringp value) (> (length value) 0)
               (not (find #\Null value)) (not (find #\Newline value))
               (not (search ".." value))
               (not (and (not allow-slashes) (or (find #\/ value) (find #\\ value))))
               (not (and allow-slashes
                         (or (char= (char value 0) #\/) (char= (char value 0) #\\)))))
    (signal-sdk-input-error (format nil "filesystem session-store ~A is unsafe" label)))
  value)

(defun %filesystem-relative-name (key)
  (%validate-session-key key)
  (let ((project (%filesystem-component (session-key-project-key key) "project key"))
        (session (%filesystem-component (session-key-session-id key) "session ID"))
        (subpath (session-key-subpath key)))
    (when subpath (%filesystem-component subpath "subpath" :allow-slashes t))
    (format nil "~A/~A~@[~@{/~A~}~].jsonl" project session subpath)))

(defun %filesystem-path (store key)
  (merge-pathnames (%filesystem-relative-name key) (filesystem-session-store-root store)))

(defun %json-line (entry)
  (with-output-to-string (stream) (yason:encode entry stream)))

(defun %filesystem-known-uuids (store key path)
  (let* ((name (%session-key-string key))
         (known (gethash name (filesystem-store-seen store))))
    (or known
        (setf (gethash name (filesystem-store-seen store))
              (let ((table (make-hash-table :test #'equal)))
                (when (probe-file path)
                  (with-open-file (stream path :direction :input)
                    (loop for line = (read-line stream nil nil)
                          while line do
                            (when (> (length line) 0)
                              (let ((uuid (%entry-id (yason:parse line))))
                                (when uuid (setf (gethash uuid table) t)))))))
                table)))))

(defmethod session-store-append ((store filesystem-session-store) key entries)
  (%validate-session-key key)
  (unless (and (listp entries) (every #'hash-table-p entries))
    (signal-sdk-input-error "session entries must be a list of JSON objects"))
  (let* ((path (%filesystem-path store key))
         (known (%filesystem-known-uuids store key path))
         (new '()))
    (dolist (entry entries)
      (let ((uuid (%entry-id entry)))
        (when (or (null uuid) (not (gethash uuid known)))
          (when uuid (setf (gethash uuid known) t))
          (push entry new))))
    (when new
      (ensure-directories-exist path)
      (with-open-file (stream path :direction :output :if-does-not-exist :create :if-exists :append)
        (dolist (entry (nreverse new))
          (write-string (%json-line entry) stream)
          (terpri stream))))
    store))

(defmethod session-store-load ((store filesystem-session-store) key)
  (let ((path (%filesystem-path store key)) (entries '()))
    (when (probe-file path)
      (with-open-file (stream path :direction :input)
        (loop for line = (read-line stream nil nil)
              while line do
                (when (> (length line) 0) (push (yason:parse line) entries)))))
    (nreverse entries)))

(defmethod session-store-list-sessions ((store filesystem-session-store) project-key)
  (let* ((project (%filesystem-component project-key "project key"))
         (directory (merge-pathnames (format nil "~A/" project) (filesystem-session-store-root store))))
    (if (probe-file directory)
        (sort (loop for file in (directory (merge-pathnames #P"*.jsonl" directory))
                    collect (pathname-name file)) #'string<)
        '())))

(defmethod session-store-list-subkeys ((store filesystem-session-store) key)
  (let* ((main (%filesystem-path store key))
         (base (make-pathname :name nil :type nil :defaults main))
         (session (session-key-session-id key))
         (subkeys '()))
    (when (probe-file base)
      (labels ((walk (directory prefix)
                 (dolist (file (directory (merge-pathnames #P"*" directory)))
                   (cond
                     ((and (null (pathname-name file)) (null (pathname-type file)))
                      (walk file (format nil "~A~A/" prefix (car (last (pathname-directory file))))))
                     ((and (string= (or (pathname-type file) "") "jsonl")
                           (not (string= (pathname-name file) session)))
                      (push (format nil "~A~A" prefix (pathname-name file)) subkeys))))))
        (walk base "")))
    (sort (remove-duplicates subkeys :test #'string=) #'string<)))
