(in-package #:claude-agent-sdk-cl)

(defstruct (session-key (:constructor make-session-key (&key project-key session-id subpath)))
  project-key session-id subpath)

(defun %validate-session-key (key)
  (unless (typep key 'session-key)
    (signal-sdk-input-error "session key must be a session-key"))
  (normalize-session-path (session-key-project-key key))
  (normalize-session-id (session-key-session-id key))
  (when (session-key-subpath key)
    (normalize-session-path (session-key-subpath key)))
  key)

(defun %session-key-string (key)
  (%validate-session-key key)
  (format nil "~A/~A~@[~@{/~A~}~]" (session-key-project-key key)
          (session-key-session-id key) (session-key-subpath key)))

(defclass session-store () ())
(defgeneric session-store-append (store key entries))
(defgeneric session-store-load (store key))
(defgeneric session-store-list-sessions (store project-key))
(defgeneric session-store-list-subkeys (store key))

(defclass in-memory-session-store (session-store)
  ((entries :initform (make-hash-table :test #'equal) :accessor store-entries)
   (seen :initform (make-hash-table :test #'equal) :accessor store-seen)
   (clock :initform 0 :accessor store-clock)))

(defun make-in-memory-session-store () (make-instance 'in-memory-session-store))

(defun %entry-id (entry)
  (and (hash-table-p entry) (gethash "uuid" entry)))

(defmethod session-store-append ((store in-memory-session-store) key entries)
  (%validate-session-key key)
  (unless (and (listp entries) (every #'hash-table-p entries))
    (signal-sdk-input-error "session entries must be a list of JSON objects"))
  (let* ((name (%session-key-string key))
         (existing (gethash name (store-entries store)))
         (seen (or (gethash name (store-seen store))
                   (setf (gethash name (store-seen store)) (make-hash-table :test #'equal)))))
    (dolist (entry entries)
      (let ((uuid (%entry-id entry)))
        (when (or (null uuid) (not (gethash uuid seen)))
          (when uuid (setf (gethash uuid seen) t))
          (setf existing (append existing (list entry))))))
    (setf (gethash name (store-entries store)) existing)
    (incf (store-clock store))
    store))

(defmethod session-store-load ((store in-memory-session-store) key)
  (copy-list (gethash (%session-key-string key) (store-entries store))))

(defmethod session-store-list-sessions ((store in-memory-session-store) project-key)
  (normalize-session-path project-key)
  (let ((ids '()))
    (maphash (lambda (name ignored)
               (declare (ignore ignored))
               (let ((prefix (format nil "~A/" project-key)))
                 (when (and (search prefix name :test #'char=) (= 0 (search prefix name :test #'char=)))
                   (let ((tail (subseq name (length prefix))))
                     (unless (search "/" tail) (push tail ids))))))
             (store-entries store))
    (sort (remove-duplicates ids :test #'string=) #'string<)))

(defmethod session-store-list-subkeys ((store in-memory-session-store) key)
  (%validate-session-key key)
  (let ((prefix (format nil "~A/~A/" (session-key-project-key key) (session-key-session-id key)))
        (subkeys '()))
    (maphash (lambda (name ignored)
               (declare (ignore ignored))
               (when (and (<= (length prefix) (length name)) (string= prefix name :end2 (length prefix)))
                 (push (subseq name (length prefix)) subkeys)))
             (store-entries store))
    (sort (remove-duplicates subkeys :test #'string=) #'string<)))

(defun session-store-mirror-message (store key message)
  "Best-effort mirror adapter hook. It accepts only typed public messages."
  (when store
    (handler-case
        (let ((entry (make-hash-table :test #'equal)))
          (setf (gethash "type" entry)
                (cond ((typep message 'assistant-message) "assistant")
                      ((typep message 'result-message) "result")
                      ((typep message 'system-message) "system")
                      ((typep message 'rate-limit-event) "rate_limit_event")
                      (t "unknown")))
          (session-store-append store key (list entry)))
      (error (condition)
        (emit-transport-log :session-store.mirror-error :condition (princ-to-string condition)))))
  message)
